name: grow_app
description: A friend will collaborate and help us manage projects, tasks, time,...

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  shared_preferences: ^2.0.8
  flutter_svg: ^0.23.0+1
  blur: ^3.0.0
  cupertino_icons: ^1.0.2
  email_validator: ^2.0.1
  custom_check_box: ^0.0.4
  iconsax: ^0.0.8
  flutter_image: ^4.1.0
  dotted_border: ^2.0.0+1
  flutter_rounded_date_picker: ^2.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  jiffy: ^5.0.0

  
  # firebase
  firebase_core: ^1.8.0
  cloud_firestore: ^2.5.4
  firebase_auth: ^3.1.4
  firebase_messaging: ^11.2.4
  overlay_support: ^1.2.1


  # sign in
  google_sign_in: ^5.2.1
  flutter_facebook_auth: ^3.5.6

  # state management
  provider: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/authentication/
    - assets/images/background/
    - assets/images/logo/
    - assets/images/onboarding/
    - assets/images/profile/

    - assets/icons/
    - assets/icons/authentication/
    - assets/icons/general/
    - assets/icons/project/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Thin.ttf
          style: normal
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ThinItalic.ttf
          style: italic
          weight: 100
        - asset: assets/fonts/poppins/Poppins-ExtraLight.ttf
          style: normal
          weight: 200
        - asset: assets/fonts/poppins/Poppins-ExtraLightItalic.ttf
          style: italic
          weight: 200
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          style: normal
          weight: 300
        - asset: assets/fonts/poppins/Poppins-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          style: normal
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          style: normal
          weight: 500
        - asset: assets/fonts/poppins/Poppins-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          style: normal
          weight: 600
        - asset: assets/fonts/poppins/Poppins-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          style: normal
          weight: 700
        - asset: assets/fonts/poppins/Poppins-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/poppins/Poppins-ExtraBold.ttf
          style: normal
          weight: 800
        - asset: assets/fonts/poppins/Poppins-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/poppins/Poppins-Black.ttf
          style: normal
          weight: 900
        - asset: assets/fonts/poppins/Poppins-BlackItalic.ttf
          style: italic
          weight: 900